---
project:
  type: website
  output-dir: docs
title: "はじめに"
format:
  html:
    toc: true
    toc-title: 目次
    toc_float: true
    toc-depth: 3
    number-sections: true
    theme: lumen
lang: ja
---

あなたは，どのような種類の協同組合があるかご存知ですか？
日常生活で協同組合を利用していますか？
あなたが普段どのくらい協同組合を意識して生活しているでしょうか？
これらのことを頭の隅に置きつつ，この授業で何をやるかを見ていきましょう。


## シラバスの確認

この授業の目的は以下のとおりです。

::: {.callout-note collapse="true" icon="false"}
## 授業の目的

協同組合の基本的な事業・組織・経営構造を正しく理解し，これからの食料および農業問題の解決のために果たしうる協同組合の役割を考える力を養う。
:::

この目的の下には，授業の到達目標があります。
この授業の単位を修得することによって，あなたは以下のことができるようになります。

::: {.callout-note collapse="true" icon="false"}
## 授業の到達目標

1. 協同組合の基本的な事業・組織・経営構造の特徴を説明できる。
2. 生活協同組合の役割を，消費者意識の変化と関連させて説明できる。
3. 農業協同組合の設立過程を，農業政策および地域農業構造の変化と関連させて説明できる。
:::

それでは，この授業でどういったことをやるのかを見ていきましょう。
これは授業概要と授業スケジュールに書かれています。

::: {.callout-note collapse="true" icon="false"}
## 授業概要

まず、協同組合設立の歴史的背景を整理した後、協同組合の基本的な事業・組織・経営構造を明らかにする。その後、日本の生活協同組合と農業協同組合について整理し、食料消費構造の変化と関連させて生協の展開過程を説明する。そして、農業政策および地域農業構造の変化と関連させて、農協の設立および展開過程について詳しく説明するとともに、食料および農業問題の解決に果たしうる協同組合の役割について考える。
:::

ここでは，授業スケジュールについては省略します。

履修者の多くは，成績が気になるでしょう。
この授業で良い成績を取りにはどうすればいいのか，何が評価されるのかといったことです。
以下の方法により，成績評価を行います。

::: {.callout-important collapse="true" icon="false"}
## 成績評価方法

- レポート 30%
- 期末試験 70%
:::

成績は期末試験の結果に左右されます。
ただし，レポートを提出しなければ，良い成績を収めることは不可能です。
また，期末試験を受けるためには，3分の2以上の授業への出席が必要です。
最初の方でサボって欠席して，5回欠席した場合，最後の方に体調不良で欠席すると欠席回数が6回となり，この授業の単位を落とすことが確定します。

授業への出席に加えて，予習・復習も必要です。
以下のことを行ってください。

::: {.callout-caution collapse="true" icon="false"}
## 授業時間外学習にかかわる情報

参考書の関連する箇所を授業時間外にあらかじめ読んでおくこと。

また，授業後には，授業中に説明した内容や関連する情報を調べ，整理しておくこと。
:::

こう言われても，何をやっていいのか分からないかもしれません。


## 予習・復習

授業中に紹介された参考書を買って読むことは予習・復習に役立つはずです。
メルカリやAmazonでは古本が手頃な価格で販売されていることがあります。
しかし，参考書をすべて買う必要はありません。
もしその参考書が図書館にあるなら，借りることで，予習・復習が効果的に行えるでしょう。
もちろん，借りるだけではダメで，内容を読む必要があります。

また，インターネットを使って調べることも効果的な予習・復習の方法のひとつです。
授業で話題にした内容が，ニュース記事等で取り上げられていたら身近な問題として理解できるかもしれません。
もしWikipediaに授業で出てきた用語の項目がある場合は，その項目を読んでください。
Wikipediaは整理されて書かれているため，効率的な学習に役立ちます。
もっと調べたいことが出てきたら，Wikipediaのページの下にある出典から，関心のある情報の元をたどることができます。

また，このサイトを読むことも授業で扱った内容の予習・復習に役立ちます。
講義ノートはMoodleから見ることができます。
ここでは，講義ノートに書かれていない情報が多くあります。
ただし，このサイトでは，あまり文章を書きません。
代わりに，RとPythonといったプログラミングが多く取り上げられています。

なぜプログラミングなのでしょうか。
実は，講義ノート作成の裏側で，RとPythonによるプログラミングは大活躍しているのです。
図表の多くは，こうしたプログラミングによって作成されています。
また，学生のうちに身につけておきたいスキルのひとつではないでしょうか。
プログラミングが得意か苦手かは人によって大きく異なると思います。
苦手なことを無理にやる必要はありません。
しかし，食わず嫌いで自分は苦手だと思い込んでいる場合，少し時間をかけてプログラミングに取り組んでみるのはどうでしょうか。

協同組合とプログラミングのどこが関係しているのか，考えた人も多いでしょう。
これらの関係性を考える必要はありません。
このサイトでは，協同組合論の予習・復習をするついでに，プログラミングを使ってみることを目指します。
予習・復習は自分のために行うものです。
このサイトでは満足できない人は，もっと多くのことを学ぶためにいろいろ調べてください。


## 準備

このサイトに書かれていることを実行するためには，あなたのパソコンでRとPythonが使える環境を構築しなければなりません。
基本的にスマートフォンは対応していないため，必ずパソコンを使ってください。

Rは [The Comprehensive R Archive Network](https://cran.r-project.org/){target="_blank"} から自分のパソコンのOSに対応したものをダウンロードし，インストールしてください。
Rの準備はこれだけです。
RStudioを使いたければ，インストールしても構いません。
ただし，もしあなたがRStudioが何をするためのアプリケーションかを理解していない婆合，Rの代替インターフェイスとしてRStudioを使うことはおすすめしません。

Pythonは，あなたのパソコンがmacOSの場合，最初からインストールされています。
Windowsの場合，最初からインストールされていないため，インストールする必要があります。
[Python.org](https://www.python.org/){target="_blank"} から自分のOSに対応したものをダウンロードし，インストールしてください（macOSではインストールする必要はありませんが，最新のバージョンを使いたいという特別な理由があればインストールしてください）。
どれをダウンロードしたらいいか分からないときは，「Latest Python 3 Release」と書かれているものをダウンロードしてください。

[Google Colaboratory](https://colab.research.google.com/){target="_blank"} を使う場合，パソコンにPythonがインストールされていなくても大丈夫です。
Google Colaboratoryはあなたが使っているOSとは無関係に，Webブラウザ上で動作します。
このサイトでは，Google Colaboratoryだけでも再現できるものが多いです。

自分のパソコンでPythonが使えるようにした後は，[Jupyter Notebook](https://jupyter.org/){target="_blank"} をインストールしてください（macOSもデフォルトの状態ではインストールされていません）。
インストール方法については説明しませんので，各自で調べてください。
Jupyter Notebookは絶対必要というわけではないので，不安な人は，Pythonに慣れてから，インストールしても構いません。

以上の説明にあるリンク先に飛んで気づいたと思います。
プログラミングに関することの多くは英語で書かれているため，簡単な英語は読めるようになってください。
日本語で説明しているサイトもありますが，何かトラブルに直面したとき，解決に役立つ情報は日本語で書かれているとは限りません。
